### ISSUE TITLE
The Future of cpp-developer-roadmap

### ISSUE THREAD

**Issue by utilForever** [utilForever/cpp-developer-roadmap#8]
Hello, I'm Chris. Long time no see!
First of all, thank you for your interest in the repository. And I'm sorry that I haven't uploaded any content for a long time. Currently,  I'm working on several open source projects such as [RosettaStone](https://github.com/utilForever/RosettaStone) and [CubbyFlow](https://github.com/CubbyFlow/CubbyFlow). Also, I'm very busy because the technology stack has changed recently as I changed jobs. The reason why I am writing like this is to talk about the future.

## Roadmap

I'll start to make the roadmap step by step. The order in which I will work in the future is as follows.

- [ ] The Basics
- [ ] Input and Output
- [ ] Types
- [ ] Reference Types
- [ ] The Object Life Cycle
- [ ] Runtime Polymorphism
- [ ] Compile-Time Polymorphism
- [ ] Expressions
- [ ] Statements
- [ ] Functions
- [ ] Testing
- [ ] Smart Pointers
- [ ] Utilities
- [ ] Containers
- [ ] Iterators
- [ ] Ranges
- [ ] Strings
- [ ] Streams
- [ ] Filesystems
- [ ] Algorithms
- [ ] Modules
- [ ] Coroutines
- [ ] Concurrency and Parallelism
---------------------------------
New Chapters (Updated 2021. 9. 21)
- [ ] Project Organization and Structure
- [ ] Network Programming
- [ ] GUI Programming
- [ ] GPU Programming

If there is no special reason, I'll update the roadmap every week. And I'll write a progress report and share it with you. I plan to finish this work by the fourth quarter of this year. Of course, I inform you that it can be postponed depending on the situation. However, I'll do our best to proceed as planned.

Please give me a lot of support so that I can complete this roadmap safely. Thank you.

**Comment by kalaluthien** [comment]
:+1: And what about:
- [x] Bit Hacks
- [x] CMakeList.txt
- [x] CUDA

**Comment by utilForever** [comment]
@kalaluthien Thanks for your suggestion. I'll add some `Bit Hacks` to chapter `Expressions` such as [Bit Tricks for Competitive Programming](https://www.geeksforgeeks.org/bit-tricks-competitive-programming/). Also, I'll add `CMake` and `CUDA` to new chapter. 😉
